// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/authOptions";
import SessionProvider from "@/utils/SessionProvider";
import Providers from "@/Providers";
import NotificationManager from "@/components/NotificationManager";


export const dynamic = "force-dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hala Ftth",
  description: "Generated by mohsen ali",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className="no-scrollbar">

      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="mx-auto max-w-10x2 text-2xl gap-2 mb-10 min-h-screen">
            <NotificationManager />
            <Providers>
              {children}
            </Providers>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}